#!/usr/bin/env python3
import multiprocessing
import os

# Creating the tuple of all the processes
first_command = '/opt/imagetagger/imagetagger.py'
for fi in range(len(os.sys.argv)-1):
    first_command += ' "' + os.sys.argv[fi+1] + '"'
all_processes = (first_command, '/opt/imagetagger/mrisa/src/server.py')

# This block of code enables us to call the script from command line.


def execute(process):
    os.system(f'python {process}')


process_pool = multiprocessing.Pool(processes=4)
process_pool.map(execute, all_processes)
